---
title: Aaron Zomback, software engineering & development
timezone: UTC
collections:
  posts:
    title: Articles
    output: true
  uploads:
    title: Uploads
    output: true
theme: jekyll-theme-minimal
